trainer:
  gpus: 1
  gradient_clip_val: 1.0
  max_epochs: 20
  log_every_n_steps: 5
  num_sanity_val_steps: 0
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'
    - class_path: pytorch_lightning.callbacks.GPUStatsMonitor
      init_args:
        fan_speed: True
        temperature: True
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 2
        save_last: True
        monitor: "val-acc"
        mode: 'max'
        filename: "{epoch:02d}-{val-acc:.3f}"
model:
  backbone: 'resnet18'
  backbone_args:
    in_channels: 3
    output_stride: 32
    weights: "ssl"
  num_classes: 10
  load: ""
  learning_rate: 3e-4
  weight_decay: 1e-4
  set_bn_eval: True
  filter_late_install: True
  with_grad_filter: True
  filter_cfgs:
    filter_install:
      - path: "backbone.layer4"
        radius: 7
        type: "resnet_layer"
  freeze_cfgs:
    - path: "backbone conv1"
    - path: "backbone bn1"
    - path: "backbone layer1"
    - path: "backbone layer2"
    - path: "backbone layer3"
    - path: "backbone layer4 [0]"
data:
  data_dir: "./data/cifar10"
  name: "cifar10"
  num_partitions: 2
  iid: False
  batch_size: 128
  train_workers: 12
  val_workers: 12
logger:
  save_dir: "runs/cls/res18"
  exp_name: "filt_last2_r7"